
package com.fantechs.provider.materialapi.imes.utils.supplierApi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_SUPPLIER_QUERY_OutService", targetNamespace = "http://leisai.com/None_ECC", wsdlLocation = "http://sappodev.leisai.com:50000/dir/wsdl?p=ic/dbb7f9ad37bf3f78b3d8b743d1a4c6a7")
public class SIMESSUPPLIERQUERYOutService
    extends Service
{

    private final static URL SIMESSUPPLIERQUERYOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESSUPPLIERQUERYOUTSERVICE_EXCEPTION;
    private final static QName SIMESSUPPLIERQUERYOUTSERVICE_QNAME = new QName("http://leisai.com/None_ECC", "SI_MES_SUPPLIER_QUERY_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sappodev.leisai.com:50000/dir/wsdl?p=ic/dbb7f9ad37bf3f78b3d8b743d1a4c6a7");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESSUPPLIERQUERYOUTSERVICE_WSDL_LOCATION = url;
        SIMESSUPPLIERQUERYOUTSERVICE_EXCEPTION = e;
    }

    public SIMESSUPPLIERQUERYOutService() {
        super(__getWsdlLocation(), SIMESSUPPLIERQUERYOUTSERVICE_QNAME);
    }

    public SIMESSUPPLIERQUERYOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESSUPPLIERQUERYOUTSERVICE_QNAME, features);
    }

    public SIMESSUPPLIERQUERYOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESSUPPLIERQUERYOUTSERVICE_QNAME);
    }

    public SIMESSUPPLIERQUERYOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESSUPPLIERQUERYOUTSERVICE_QNAME, features);
    }

    public SIMESSUPPLIERQUERYOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESSUPPLIERQUERYOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESSUPPLIERQUERYOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESSUPPLIERQUERYOut getHTTPPort() {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTP_Port"), SIMESSUPPLIERQUERYOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESSUPPLIERQUERYOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESSUPPLIERQUERYOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTP_Port"), SIMESSUPPLIERQUERYOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESSUPPLIERQUERYOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESSUPPLIERQUERYOut getHTTPSPort() {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTPS_Port"), SIMESSUPPLIERQUERYOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESSUPPLIERQUERYOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESSUPPLIERQUERYOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTPS_Port"), SIMESSUPPLIERQUERYOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESSUPPLIERQUERYOUTSERVICE_EXCEPTION!= null) {
            throw SIMESSUPPLIERQUERYOUTSERVICE_EXCEPTION;
        }
        return SIMESSUPPLIERQUERYOUTSERVICE_WSDL_LOCATION;
    }

}
