
package com.fantechs.provider.materialapi.imes.utils.badnessCategoryApi;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_BADCODE_QUERY_OutService", targetNamespace = "http://leisai.com/None_ECC", wsdlLocation = "http://sappoprd.leisai.com:50000/dir/wsdl?p=ic/8b4f43d3f01934ea8f398285e16ad1bc")
public class SIMESBADCODEQUERYOutService
    extends Service
{

    private final static URL SIMESBADCODEQUERYOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESBADCODEQUERYOUTSERVICE_EXCEPTION;
    private final static QName SIMESBADCODEQUERYOUTSERVICE_QNAME = new QName("http://leisai.com/None_ECC", "SI_MES_BADCODE_QUERY_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sappoprd.leisai.com:50000/dir/wsdl?p=ic/8b4f43d3f01934ea8f398285e16ad1bc");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESBADCODEQUERYOUTSERVICE_WSDL_LOCATION = url;
        SIMESBADCODEQUERYOUTSERVICE_EXCEPTION = e;
    }

    public SIMESBADCODEQUERYOutService() {
        super(__getWsdlLocation(), SIMESBADCODEQUERYOUTSERVICE_QNAME);
    }

    public SIMESBADCODEQUERYOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESBADCODEQUERYOUTSERVICE_QNAME, features);
    }

    public SIMESBADCODEQUERYOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESBADCODEQUERYOUTSERVICE_QNAME);
    }

    public SIMESBADCODEQUERYOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESBADCODEQUERYOUTSERVICE_QNAME, features);
    }

    public SIMESBADCODEQUERYOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESBADCODEQUERYOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESBADCODEQUERYOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESBADCODEQUERYOut getHTTPPort() {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTP_Port"), SIMESBADCODEQUERYOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESBADCODEQUERYOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESBADCODEQUERYOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTP_Port"), SIMESBADCODEQUERYOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESBADCODEQUERYOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESBADCODEQUERYOut getHTTPSPort() {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTPS_Port"), SIMESBADCODEQUERYOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESBADCODEQUERYOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESBADCODEQUERYOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTPS_Port"), SIMESBADCODEQUERYOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESBADCODEQUERYOUTSERVICE_EXCEPTION!= null) {
            throw SIMESBADCODEQUERYOUTSERVICE_EXCEPTION;
        }
        return SIMESBADCODEQUERYOUTSERVICE_WSDL_LOCATION;
    }

}
