server:
  port: 9028
  max-http-header-size: 10000000

spring:
  profiles:
    include: dev
  application:
    name: @pom.artifactId@
  datasource:
    primary:
      jdbc-url: jdbc:sqlserver://192.168.200.9:1433;DatabaseName=LSDB1
      type: com.alibaba.druid.pool.DruidDataSource
      username: sa
      password: 00000
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver


logging:
  file: /data/logs/ocean/@pom.artifactId@/info/@pom.artifactId@.log