server:
  port: 9028
  max-http-header-size: 10000000

spring:
  profiles:
    include: dev
  application:
    name: @pom.artifactId@
  datasource:
    primary:
      jdbc-url: jdbc:sqlserver://172.16.60.27:1433;DatabaseName=LS2019
      type: com.alibaba.druid.pool.DruidDataSource
      username: jfmes
      password: abcd-1234
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

logging:
  file: /data/logs/ocean/@pom.artifactId@/info/@pom.artifactId@.log