server:
  port: 8802
  maxHttpHeaderSize: 10000000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#  rabbitmq:
#    host: 192.168.204.159
#    port: 5672
#    username: admin
#    password: admin
  rabbitmq:
    #host: 192.168.61.55
    host: 192.168.204.164
    #host: 192.168.204.159
    port: 5672
    username: admin
    #password: admin
    password: StrongPassword
    # 消息发送至exchange callback
    publisher-confirms: true
    # 消息发送至queue 失败才callback
    publisher-returns: true
    # 消费消息手动删除
    listener:
      simple:
        acknowledge-mode: manual
  mail:
    host: smtp.qq.com
    username: 1613582568@qq.com
    password: vnvnancndwoyecfb
    port: 587
    protocol: smtp
    default-encoding: UTF-8
print:
  ip: 192.168.150.223
  port: 8098
