server:
  port: 8802
  maxHttpHeaderSize: 10000000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#  rabbitmq:
#    host: 192.168.204.159
#    port: 5672
#    username: admin
#    password: admin
  mail:
    host: smtp.qq.com
    username: 1613582568@qq.com
    password: vnvnancndwoyecfb
    port: 587
    protocol: smtp
    default-encoding: UTF-8
print:
  ip: 192.168.104.103
  port: 8098
