
package com.fantechs.provider.materialapi.imes.utils.pushMessage;

import com.fantechs.common.base.general.dto.restapi.Mpnewsmsginput;
import com.fantechs.common.base.general.dto.restapi.Resbase;
import com.fantechs.common.base.general.dto.restapi.Textmsginput;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendMsg", targetNamespace = "http://ws.leige.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendMsg {


    /**
     * 
     * @param arg0
     * @return
     *     returns testClient.Resbase
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMpnewsMessage", targetNamespace = "http://ws.leige.com/", className = "testClient.SendMpnewsMessage")
    @ResponseWrapper(localName = "sendMpnewsMessageResponse", targetNamespace = "http://ws.leige.com/", className = "testClient.SendMpnewsMessageResponse")
    @Action(input = "http://ws.leige.com/SendMsg/sendMpnewsMessageRequest", output = "http://ws.leige.com/SendMsg/sendMpnewsMessageResponse")
    public Resbase sendMpnewsMessage(
            @WebParam(name = "arg0", targetNamespace = "")
                    Mpnewsmsginput arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns testClient.Resbase
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://ws.leige.com/", className = "testClient.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://ws.leige.com/", className = "testClient.SendMessageResponse")
    @Action(input = "http://ws.leige.com/SendMsg/sendMessageRequest", output = "http://ws.leige.com/SendMsg/sendMessageResponse")
    public Resbase sendMessage(
            @WebParam(name = "arg0", targetNamespace = "")
                    Textmsginput arg0);

}
