server:
  port: 9001
  max-http-header-size: 10000000

spring:
  profiles:
    include: leisai
  application:
    name: @pom.artifactId@
ribbon:
  ConnectTimeout: 50000 # 连接超时时间(ms)
  ReadTimeout: 50000 # 通信超时时间(ms)

logging:
  file: /data/logs/ocean/@pom.artifactId@/info/@pom.artifactId@.log