server:
  port: 9001
  max-http-header-size: 10000000

spring:
  profiles:
    include: leisai
  application:
    name: @pom.artifactId@

logging:
  file: /data/logs/ocean/@pom.artifactId@/info/@pom.artifactId@.log