server:
  port: 10010
  maxHttpHeaderSize: 10000000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  rabbitmq:
    host: 10.10.20.62
#    host: 10.10.200.33
#    host: 192.168.204.163
    port: 5672
    username: admin
#    password: admin
    password: StrongPassword
    # 消息发送至exchange callback
    publisher-confirms: true
    # 消息发送至queue 失败才callback
    publisher-returns: true
    # 消费消息手动删除
    listener:
      simple:
        acknowledge-mode: manual
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
wmsAPI:
#  finishPtlJobOrderUrl: http://wms.8ma.net:8090/bmwms/ptl/finishOrder
  finishPtlJobOrderUrl: http://10.10.20.61/bmwms/ptl/finishOrder