server:
  port: 10010
  maxHttpHeaderSize: 10000000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  rabbitmq:
    #host: 192.168.61.55
    host: 192.168.204.164
    port: 5672
    username: admin
#    password: admin
    password: StrongPassword
    # 消息发送至exchange callback
    publisher-confirms: true
    # 消息发送至queue 失败才callback
    publisher-returns: true
    # 消费消息手动删除
    listener:
      simple:
        acknowledge-mode: manual
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
wmsAPI:
  finishPtlJobOrderUrl: http://129.211.33.122:8090/ptl/finishOrder