server:
  port: 10010
  maxHttpHeaderSize: 10000000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  rabbitmq:
    #host: 192.168.61.55
    host: 10.182.163.191
    port: 5672
    username: admin
    #password: admin
    password: StrongPassword
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mesAPI:
  resApi: http://10.182.163.82:8099/getForPtlAPI/getPtlSortingOrder
qisAPI:
  confirmInBillOrder: http://192.168.200.237:8180/qisapi/api/confirmInBillOrder
  confirmOutBillOrder: http://192.168.200.237:8180/qisapi/api/confirmOutBillOrder