server:
  port: 10010
  maxHttpHeaderSize: 10000000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  rabbitmq:
    host: 192.168.200.94
    port: 5672
    username: jiangfan
    password: 123456
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

