server:
  port: 10010
  maxHttpHeaderSize: 10000000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  rabbitmq:
    #host: 192.168.61.55
    host: 192.168.204.164
    port: 5672
    username: admin
#    password: admin
    password: StrongPassword
    # 消息发送至exchange callback
    publisher-confirms: true
    # 消息发送至queue 失败才callback
    publisher-returns: true
    # 消费消息手动删除
    listener:
      simple:
        acknowledge-mode: manual
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mesAPI:
  resApi: http://192.168.61.43:8099/getForPtlAPI/getPtlSortingOrder
#  resApi: http://10.182.163.82:8099/getForPtlAPI/getPtlSortingOrder
qisAPI:
  confirmInBillOrder: http://14.18.66.233:8092/qisapi/api/confirmInBillOrder
  confirmOutBillOrder: http://14.18.66.233:8092/qisapi/api/confirmOutBillOrder
#  confirmInBillOrder: http://192.168.200.237:8180/qisapi/api/confirmInBillOrder
#  confirmOutBillOrder: http://192.168.200.237:8180/qisapi/api/confirmOutBillOrder