
package com.fantechs.provider.baseapi.esop.utils.reportWorkApi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_WORKORDER_REPORT_SAVE_OutService", targetNamespace = "http://leisai.com/None_ECC", wsdlLocation = "http://sappodev.leisai.com:50000/dir/wsdl?p=ic/112f809eacc7313faee6f09a85f1268e")
public class SIMESWORKORDERREPORTSAVEOutService
    extends Service
{

    private final static URL SIMESWORKORDERREPORTSAVEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESWORKORDERREPORTSAVEOUTSERVICE_EXCEPTION;
    private final static QName SIMESWORKORDERREPORTSAVEOUTSERVICE_QNAME = new QName("http://leisai.com/None_ECC", "SI_MES_WORKORDER_REPORT_SAVE_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sappodev.leisai.com:50000/dir/wsdl?p=ic/112f809eacc7313faee6f09a85f1268e");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESWORKORDERREPORTSAVEOUTSERVICE_WSDL_LOCATION = url;
        SIMESWORKORDERREPORTSAVEOUTSERVICE_EXCEPTION = e;
    }

    public SIMESWORKORDERREPORTSAVEOutService() {
        super(__getWsdlLocation(), SIMESWORKORDERREPORTSAVEOUTSERVICE_QNAME);
    }

    public SIMESWORKORDERREPORTSAVEOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESWORKORDERREPORTSAVEOUTSERVICE_QNAME, features);
    }

    public SIMESWORKORDERREPORTSAVEOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESWORKORDERREPORTSAVEOUTSERVICE_QNAME);
    }

    public SIMESWORKORDERREPORTSAVEOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESWORKORDERREPORTSAVEOUTSERVICE_QNAME, features);
    }

    public SIMESWORKORDERREPORTSAVEOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESWORKORDERREPORTSAVEOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESWORKORDERREPORTSAVEOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESWORKORDERREPORTSAVEOut getHTTPPort() {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTP_Port"), SIMESWORKORDERREPORTSAVEOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESWORKORDERREPORTSAVEOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESWORKORDERREPORTSAVEOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTP_Port"), SIMESWORKORDERREPORTSAVEOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESWORKORDERREPORTSAVEOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESWORKORDERREPORTSAVEOut getHTTPSPort() {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTPS_Port"), SIMESWORKORDERREPORTSAVEOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESWORKORDERREPORTSAVEOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESWORKORDERREPORTSAVEOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTPS_Port"), SIMESWORKORDERREPORTSAVEOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESWORKORDERREPORTSAVEOUTSERVICE_EXCEPTION!= null) {
            throw SIMESWORKORDERREPORTSAVEOUTSERVICE_EXCEPTION;
        }
        return SIMESWORKORDERREPORTSAVEOUTSERVICE_WSDL_LOCATION;
    }

}
