server:
  max-http-header-size: 10000000
  undertow:
     max-http-post-size: 0
     buffer-size: 1024
     direct-buffers: true

spring:
  datasource:
    url: jdbc:mysql://10.182.163.191:3306/ocean?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    #url: jdbc:mysql://10.182.163.246:3306/newenergy_mes?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.182.163.81
    port: 6379
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
mybatis:
  config-location: classpath:myBatis-config.xml
  mapper-locations: classpath:mapper/*.xml


#注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 60000
  ReadTimeout: 60000

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

feign:
  hystrix:
    enabled: false
  httpclient:
        enabled: true
        connection-timeout: 60000
  compression:
    request:
      enabled: true
      mime-type: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

##关闭hystrix 超时
hystrix.command.default.execution.timeout.enabled: false

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS