spring:
  datasource:
    url: jdbc:mysql://10.182.163.191:3306/icloud_dm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 10.182.163.81
    port: 6379
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
mybatis:
  config-location: classpath:myBatis-config.xml
  mapper-locations: classpath:mapper/*.xml


#注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true