server:
  max-http-header-size: 10000000
  undertow:
    max-http-post-size: 0
    buffer-size: 1024
    direct-buffers: true

spring:
  datasource:
    url: jdbc:mysql://10.10.200.34:3306/ocean?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: bmwms_ptl
    password: wTZ2rf5PeFCFtfAc
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 初始连接数
    initialSize: 5
    # 最小连接池数量
    minIdle: 10
    # 最大连接池数量
    maxActive: 30
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #配置从连接池获取连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
    testOnBorrow: false
    #配置向连接池归还连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
    testOnReturn: false
    #打开PsCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    #合并多个DruidDatasource的监控数据
    useGlobalDataSourceStat: true
    #通过connectProperties属性来打开mergesql功能罗慢sQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;
  redis:
    host: 10.10.200.33
    port: 6379
    password: 'qwe!@#'
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
mybatis:
  config-location: classpath:myBatis-config.xml
  mapper-locations: classpath:mapper/*.xml


#注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://root:root@10.10.200.33:8761/eureka/
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 60000
  ReadTimeout: 60000

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
    connection-timeout: 60000
  compression:
    request:
      enabled: true
      mime-type: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

##关闭hystrix 超时
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.isolation.thread.timeoutInMilliseconds: 70000

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS