server:
  port: 8762
  max-http-header-size: 10000000

spring:
  profiles:
    include: xinbao
  application:
      name: @pom.artifactId@
  main:
    allow-bean-definition-overriding: true

license:
  subject: JF001
  publicAlias: publicCert
  storePass: public_password1234
  licensePath: D:/license/license.lic
  publicKeysStorePath: D:/keytool/publicCerts.keystore

logging:
  file: /data/logs/ocean/@pom.artifactId@/info/@pom.artifactId@.log