
package com.fantechs.provider.materialapi.imes.utils.materialApi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_MATERIAL_QUERY_OutService", targetNamespace = "http://leisai.com/None_ECC", wsdlLocation = "http://sappodev.leisai.com:50000/dir/wsdl?p=ic/098215a2ef473d4aaa6e4701f24f3cde")
public class SIMESMATERIALQUERYOutService
    extends Service
{

    private final static URL SIMESMATERIALQUERYOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESMATERIALQUERYOUTSERVICE_EXCEPTION;
    private final static QName SIMESMATERIALQUERYOUTSERVICE_QNAME = new QName("http://leisai.com/None_ECC", "SI_MES_MATERIAL_QUERY_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sappodev.leisai.com:50000/dir/wsdl?p=ic/098215a2ef473d4aaa6e4701f24f3cde");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESMATERIALQUERYOUTSERVICE_WSDL_LOCATION = url;
        SIMESMATERIALQUERYOUTSERVICE_EXCEPTION = e;
    }

    public SIMESMATERIALQUERYOutService() {
        super(__getWsdlLocation(), SIMESMATERIALQUERYOUTSERVICE_QNAME);
    }

    public SIMESMATERIALQUERYOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESMATERIALQUERYOUTSERVICE_QNAME, features);
    }

    public SIMESMATERIALQUERYOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESMATERIALQUERYOUTSERVICE_QNAME);
    }

    public SIMESMATERIALQUERYOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESMATERIALQUERYOUTSERVICE_QNAME, features);
    }

    public SIMESMATERIALQUERYOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESMATERIALQUERYOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESMATERIALQUERYOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESMATERIALQUERYOut getHTTPPort() {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTP_Port"), SIMESMATERIALQUERYOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESMATERIALQUERYOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESMATERIALQUERYOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTP_Port"), SIMESMATERIALQUERYOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESMATERIALQUERYOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESMATERIALQUERYOut getHTTPSPort() {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTPS_Port"), SIMESMATERIALQUERYOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESMATERIALQUERYOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESMATERIALQUERYOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://leisai.com/None_ECC", "HTTPS_Port"), SIMESMATERIALQUERYOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESMATERIALQUERYOUTSERVICE_EXCEPTION!= null) {
            throw SIMESMATERIALQUERYOUTSERVICE_EXCEPTION;
        }
        return SIMESMATERIALQUERYOUTSERVICE_WSDL_LOCATION;
    }

}
