
/*=============================================2021-9-7 leifengzhi ============================*/
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (56, '01', '产品条码', '产品条码标签', 1, 1, '产品条码', 29, 1, '2021-04-15 16:27:00', 1, '2021-04-21 10:24:54', NULL, NULL, NULL, NULL);
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (57, '02', '销售订单条码', '销售订单条码标签', 2, 1, '销售订单条码', 29, 1, '2021-04-15 16:28:00', 1, '2021-05-10 15:47:46', NULL, NULL, NULL, NULL);
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (58, '03', '客户条码', '客户条码标签', 2, 1, '客户条码', 29, 1, '2021-04-15 16:28:35', 1, '2021-04-15 16:28:35', NULL, NULL, NULL, NULL);
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (59, '04', '部件条码', '部件条码标签', 2, 1, '部件条码', 29, 1, '2021-04-15 16:29:31', 1, '2021-04-15 16:29:31', NULL, NULL, NULL, NULL);
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (60, '05', '工单流转单', '工单流转单标签', 2, 1, '工单流转单', 29, 1, '2021-04-15 16:30:13', 1, '2021-04-15 16:30:13', NULL, NULL, NULL, NULL);
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (61, '06', '工单流转卡', '工单流转卡标签', 2, 1, '工单流转卡', 29, 1, '2021-04-15 16:31:00', 1, '2021-04-20 17:32:48', NULL, NULL, NULL, NULL);
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (62, '07', '工单流转卡条码', '工单流转卡条码标签', 2, 1, '工单流转卡条码', 29, 1, '2021-04-15 16:32:00', 1, '2021-04-20 17:32:49', NULL, NULL, NULL, NULL);
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (63, '08', '彩盒条码', '彩盒条码标签', 2, 1, '彩盒条码', 29, 1, '2021-04-15 16:32:00', 1, '2021-04-20 17:32:52', NULL, NULL, NULL, NULL);
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (64, '09', '包箱条码', '包箱条码标签', 2, 1, '包箱条码', 29, 1, '2021-04-15 16:33:00', 1, '2021-05-26 16:38:33', NULL, NULL, NULL, NULL);
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (73, '10', '栈板条码', '栈板条码标签', 2, 1, '栈板条码', 29, 138, '2021-05-13 17:28:19', 138, '2021-05-13 17:28:19', NULL, NULL, NULL, NULL);
INSERT INTO `fantech_imes_v2`.`base_label_category` (`label_category_id`, `label_category_code`, `label_category_name`, `label_category_desc`, `barcode_type`, `status`, `remark`, `org_id`, `create_user_id`, `create_time`, `modified_user_id`, `modified_time`, `is_delete`, `option1`, `option2`, `option3`) VALUES (75, 'SYS-BL01', '默认模板', '打印模板', 2, 1, '打印模板', 29, 141, '2021-07-13 16:17:00', 141, '2021-07-16 14:04:02', NULL, NULL, NULL, NULL);
/*===========================================   end   ========================================/
