
package com.fantechs.provider.materialapi.imes.utils.reportWorkApi;

import com.fantechs.common.base.general.dto.restapi.DTMESWORKORDERREPORTSAVEREQ;
import com.fantechs.common.base.general.dto.restapi.DTMESWORKORDERREPORTSAVERES;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MES_WORKORDER_REPORT_SAVE_Out", targetNamespace = "http://leisai.com/None_ECC")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMESWORKORDERREPORTSAVEOut {


    /**
     * 
     * @param mtMESWORKORDERREPORTSAVEREQ
     * @return
     *     returns testClient.DTMESWORKORDERREPORTSAVERES
     */
    @WebMethod(operationName = "SI_MES_WORKORDER_REPORT_SAVE_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_MES_WORKORDER_REPORT_SAVE_RES", targetNamespace = "http://leisai.com/ECC", partName = "MT_MES_WORKORDER_REPORT_SAVE_RES")
    public DTMESWORKORDERREPORTSAVERES siMESWORKORDERREPORTSAVEOut(
            @WebParam(name = "MT_MES_WORKORDER_REPORT_SAVE_REQ", targetNamespace = "http://leisai.com/ECC", partName = "MT_MES_WORKORDER_REPORT_SAVE_REQ")
                    DTMESWORKORDERREPORTSAVEREQ mtMESWORKORDERREPORTSAVEREQ);

}
