server:
  port: 9000
  max-http-header-size: 10000000

spring:
  profiles:
    include: dev
  application:
    name: @pom.artifactId@
  datasource:
    primary:
      jdbc-url: jdbc:mysql://10.182.163.191:3306/fantech_imes?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,logback
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    secondary:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://10.182.164.248:1433;DatabaseName=newenergy_mes
      username: sa
      password: Jf@2020
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    host: 10.182.163.246
    port: 6379
    password:
    jackson:
      date-format: yyyy-MM-dd HH:mm
      time-zone: GMT+8

logging:
  file: /data/logs/ocean/@pom.artifactId@/info/@pom.artifactId@.log

##对接QIS
server-url:
  qisGetNewUpdateCW: http://10.182.163.71:8080/qisapi/api/getNewUpdateCW

constant-base:
  defaultOrgId: 1001802050000491
  newOrgId: 1002001095622859
  API_LASTUPDATE_TIME_CW: 2017
  defaultOrgNum: N
  defaultOrgName: 广东纽恩泰新能源科技发展有限公司