server:
  port: 8769
  max-http-header-size: 10000000

spring:
  profiles:
    include: leisai
  application:
    name: @pom.artifactId@
  type: com.alibaba.druid.pool.DruidDataSource
  datasource:
#    url: jdbc:mysql://192.168.204.164:3306/fantech_imes_v2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    username: root
#    password: 123456
    url: jdbc:mysql://172.16.60.35:3306/fantech_imes_v2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: qwe!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

## UReport2 配置文件
ureport:
    disableHttpSessionReportCache: false
    disableFileProvider: false
    fileStoreDir: D:/ureportfiles
    debug: true
logging:
  file: /data/logs/ocean/@pom.artifactId@/info/@pom.artifactId@.log
