server:
  port: 9015
  maxHttpHeaderSize: 10000000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
logging:
  file: /data/logs/ocean/@pom.artifactId@/info/@pom.artifactId@.log