server:
  port: 8777
  max-http-header-size: 10000000

spring:
  profiles:
    include: dev
  application:
    name: @pom.artifactId@
  main:
    allow-bean-definition-overriding: true
#logging:
#  file: /data/logs/ocean/@pom.artifactId@/info/@pom.artifactId@.log