server:
  max-http-header-size: 10000000
  undertow:
    max-http-post-size: 0
    buffer-size: 1024
    direct-buffers: true

spring:
  datasource:
    url: jdbc:mysql://192.168.100.96:3306/fantech_imes?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: xjt***1A
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #  filters: stat,wall,logback
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 192.168.100.96
    #host: 10.182.163.246
    port: 6379
    password: 'qwe!@#'
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
mybatis:
  config-location: classpath:myBatis-config.xml
  mapper-locations: classpath:mapper/*.xml


#注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://root:root@192.168.100.96:8761/eureka/
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxConnectionsPerHost: 50
  MaxTotalConnections: 200

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
    connection-timeout: 60000
  compression:
    request:
      enabled: true
      mime-type: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

##关闭hystrix 超时
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.isolation.thread.timeoutInMilliseconds: 70000

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-per-route-connections: 20
    max-total-connections: 200

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

##对接U9
server-url:
  qisGetNewUpdateCW: http://10.182.163.71:8080/qisapi/api/getNewUpdateCW

constant-base:
  defaultOrgId: 1001802050000491
  API_LASTUPDATE_TIME_CW: 2017
  defaultOrgNum: N
  defaultOrgName: 广东纽恩泰新能源科技发展有限公司

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认12小时, -1代表永不过期
  timeout: 43200
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false