server:
  max-http-header-size: 10000000
  undertow:
    max-http-post-size: 0
    buffer-size: 1024
    direct-buffers: true
  tomcat:
    basedir:  /tmp/tomcat
spring:
  datasource:
    url: jdbc:mysql://192.168.5.86:3306/fantech_imes_v2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #  filters: stat,wall,logback
      filters: stat,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: root
        login-password: 123456
        ##deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问
        allow:
        deny:
  redis:
    host: localhost
    #host: 10.182.163.246
    port: 6379
    password: qwe!@#

  rabbitmq:
    host: 192.168.5.85
    port: 5672
    username: admin
    #password: admin
    password: StrongPassword
    # 消息发送至exchange callback
    publisher-confirms: true
    # 消息发送至queue 失败才callback
    publisher-returns: true
    # 消费消息手动删除
    listener:
      simple:
        acknowledge-mode: manual

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis:
  config-location: classpath:myBatis-config.xml
  mapper-locations: classpath:mapper/*.xml


#注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://root:Wms123@localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxConnectionsPerHost: 50
  MaxTotalConnections: 200

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
    connection-timeout: 6000000
  compression:
    request:
      enabled: true
      mime-type: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

##关闭hystrix 超时
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.isolation.thread.timeoutInMilliseconds: 70000

zuul:
  host:
    connect-timeout-millis: 6000000
    socket-timeout-millis: 6000000
    max-per-route-connections: 20
    max-total-connections: 200

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: false
  endpoint:
    health:
      show-details: ALWAYS
    env:
      enabled: false
    metrics:
      enabled: true
#提高日志级别为WARN
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
