server:
  max-http-header-size: 10000000
  undertow:
    max-http-post-size: 0
    buffer-size: 1024
    direct-buffers: true

spring:
  datasource:
    url: jdbc:mysql://192.168.18.110:3306/fantech_imes_v2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: wms
    password: mulinsen.123
#    url: jdbc:mysql://192.168.200.181:3306/fantech_imes_v2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: hl123.@2021
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #  filters: stat,wall,logback
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 192.168.18.109
    port: 6379
    password: hlredis#2018
#    host: 192.168.200.181
#    port: 6379
#    password: qwe!@#
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
mybatis:
  config-location: classpath:myBatis-config.xml
  mapper-locations: classpath:mapper/*.xml


#注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://root:root@192.168.18.107:8761/eureka/
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxConnectionsPerHost: 50
  MaxTotalConnections: 200

tx-lcn:
  client:
    manager-address: 192.168.18.107:8070

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
    connection-timeout: 60000
  compression:
    request:
      enabled: true
      mime-type: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

##关闭hystrix 超时
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.isolation.thread.timeoutInMilliseconds: 70000

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-per-route-connections: 20
    max-total-connections: 200

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

##对接U9
server-url:
  qisGetNewUpdateCW: http://10.182.163.71:8080/qisapi/api/getNewUpdateCW

constant-base:
  defaultOrgId: 1001802050000491
  API_LASTUPDATE_TIME_CW: 2017
  defaultOrgNum: N
  defaultOrgName: 广东纽恩泰新能源科技发展有限公司
