server:
  port: 8763
  max-http-header-size: 10000000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
        - VM.*
      preferredNetworks:
        - 192.168
